# 베이스 이미지 사용
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG SSH_USER=${SSH_USER:-ubuntu}
ARG SSH_PASSWORD=${SSH_PASSWORD:-ubuntu}

ENV SSH_USER=${SSH_USER}
ENV SSH_PASSWORD=${SSH_PASSWORD}

ARG SOURCE=https://github.com/Yelp/dumb-init/releases/download
ENV TZ=Asia/Seoul
ADD $SOURCE/v1.2.5/dumb-init_1.2.5_amd64.deb /tmp/
# 타임존 설정
RUN echo $TZ > /etc/timezone

# 패키지 설치 및 정리
RUN sed -i "s#/archive.ubuntu.com/#/mirror.kakao.com/#g" /etc/apt/sources.list && \
    apt-get update -qq && \
    apt-get install -qq -y \
        apt-utils \
        aptitude \
        dnsutils \
        iputils-ping \
        net-tools \
        netcat \
        openssh-server \
        ssh \
        sudo \
        telnet \
        traceroute \
        vim \
        python3 \
        python3-pip && \
    apt-get clean -qq autoclean && \
    apt-get autoremove -qq --yes && \
    rm -rf /var/lib/apt/lists /var/lib/dpkg/info /tmp/* /var/tmp/*

USER root

# SSH Key 설정
COPY id_rsa /home/$SSH_USER/.ssh/id_rsa
COPY id_rsa.pub /home/$SSH_USER/.ssh/authorized_keys.pub

RUN useradd -c "System Administrator" -m -d /home/$SSH_USER \
            -s /bin/bash $SSH_USER \
    && usermod -aG sudo $SSH_USER \ 
    && chown $SSH_USER.$SSH_USER /home/$SSH_USER/.ssh \ 
    && echo "$SSH_USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \ 
    && echo "$SSH_USER:$SSH_PASSWORD" | chpasswd

# SSH 서버 설정
RUN mkdir /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication no/PasswordAuthentication no/g' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/' /etc/ssh/ssh_config

# authorized_keys 설정
RUN cat /home/$SSH_USER/.ssh/authorized_keys.pub >> /home/$SSH_USER/.ssh/authorized_keys && \
    chown -R $SSH_USER:$SSH_USER /home/$SSH_USER/.ssh && \
    chmod 700 /home/$SSH_USER/.ssh && \
    chmod 600 /home/$SSH_USER/.ssh/*
RUN chmod 600 /home/$SSH_USER/.ssh/authorized_keys


# SSH 포트 노출 및 서버 시작
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
